# responsible for maintaining a specific number of replica pods running in the cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin # select pods with label 'app: zipkin' to manage
  template:
    metadata:
      labels:
        app: zipkin # define labels to apply to pods creadted by this deployment
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:latest
        ports:
        - containerPort: 9411 # expose 9411 port within this container